#ifndef BM_BM_SIM_RUNTIME_RECONFIG_ERROR_CODES_H_
#define BM_BM_SIM_RUNTIME_RECONFIG_ERROR_CODES_H_

namespace bm {

enum class RuntimeReconfigErrorCode {
  SUCCESS = 0,
  P4OBJECTS_INIT_FAIL,
  OPEN_JSON_FILE_FAIL,
  OPEN_PLAN_FILE_FAIL,
  DUP_CHECK_ERROR,
  PREFIX_ERROR,
  UNFOUND_ID_ERROR,
  UNSUPPORTED_TARGET_ERROR,
  DELETE_ID_FAIL,
  INVALID_COMMAND_ERROR,
  INVALID_HASH_FUNCTION_NAME_ERROR,
  OPEN_OUTPUT_FILE_FAIL,
};

}  // namespace bm

#endif  // BM_BM_SIM_RUNTIME_RECONFIG_ERROR_CODES_H_